---
- name: create glance user
  script:  /root/servertest/roles/glance/tasks/glance.sh


- name: install glance
  apt:
    name:
      - glance


- name: backup glance file
  command: mv /etc/glance/glance-api.conf /etc/glance/glance-api.conf.org


- name: compile glance file
  command: cp ~/servertest/roles/glance/tasks/glance-api.conf /etc/glance/glance-api.conf


- name: change access status
  file:
    path: /etc/glance/glance-api.conf
    state: file
    owner: root
    group: glance
    mode: 0640


- name: check 8774-port
  command: "ss -ltun"
  register: command2_result

- name: Perform a glance DB sync
  command: su -s /bin/bash glance -c "glance-manage db_sync"
  when: "':8774' not in command2_result.stdout"


- name:	restart glance
  service: name=glance-api state=restarted
  when: "':8774' not in command2_result.stdout"


- name: install kvm
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-daemon
      - virtinst
      - bridge-utils
      - libosinfo-bin
      - libguestfs-tools
      - virt-top
