---
- name: install mariadb
  apt:
    name:
      - mariadb-server


- name: text code config
  replace: dest=/etc/mysql/mariadb.conf.d/50-server.cnf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^collation-server      = utf8mb4_general_ci', replace: '#collation-server      = utf8mb4_general_ci' }


- name: restart mariadb
  service: name=mariadb state=restarted


- name: install needed software
  apt:
    name:
      - software-properties-common 


- name: check victoria repository
  command: ls /etc/apt/sources.list.d
  register: check_vic_rep


- name: Ensure to add repository
  shell: add-apt-repository cloud-archive:victoria
  when: "'cloudarchive-victoria.list' not in check_vic_rep.stdout"


- name: apt update
  apt:
    update_cache: yes


- name: apt upgrade
  apt:
    upgrade: yes


- name: install rabbitMQ
  apt:
    name:
      - rabbitmq-server
      - memcached
      - python3-pymysql


- name: rabbit user create
  rabbitmq_user: user=openstack
                 password=password
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: bind-address register
  replace: dest=/etc/mysql/mariadb.conf.d/50-server.cnf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^bind-address            = 127.0.0.1', replace: 'bind-address            = 0.0.0.0' }


- name: chenge max_conection
  lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf
              insertafter='^#myisam_recover_options = BACKUP'
              line="{{item.line}}"
  with_items:
    - { line: 'max_connections = 500' }


- name: bind-address register
  replace: dest=/etc/memcached.conf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
     - { regexp: '^-l 127.0.0.1', replace: '-l 0.0.0.0' }


- name: install expect
  apt:
    name:
      - expect


- name: set root password
  script:  /root/openstackope/roles/mariadb/tasks/sql.sh
  

- name: restart mariadb
  service: name=mariadb state=restarted


- name: restart rabbitMQ
  service: name=rabbitmq-server state=restarted

     
- name: restart memcached
  service: name=memcached state=restarted


#- name: create dummy db
  #mysql_db: name=test state=present 


- name: create keystone user
  script: /root/openstackope/roles/mariadb/tasks/sql.sh 
