---
- name: install ntp component
  apt:
    name:
      - chrony

- name: deactivate default setting
  replace: dest=/etc/chrony/chrony.conf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^pool ntp.ubuntu.com        iburst maxsources 4', replace: '#pool ntp.ubuntu.com        iburst maxsources 4' }
    - { regexp: '^pool 0.ubuntu.pool.ntp.org iburst maxsources 1', replace: '#pool 0.ubuntu.pool.ntp.org iburst maxsources 1' }
    - { regexp: '^pool 1.ubuntu.pool.ntp.org iburst maxsources 1', replace: '#pool 1.ubuntu.pool.ntp.org iburst maxsources 1' }
    - { regexp: '^pool 2.ubuntu.pool.ntp.org iburst maxsources 2', replace: '#pool 2.ubuntu.pool.ntp.org iburst maxsources 2' }


- name: insert time zone
  lineinfile: dest=/etc/chrony/chrony.conf
              insertafter='#pool 2.ubuntu.pool.ntp.org iburst maxsources 2'
              line="{{item.line}}"
  with_items:
    - { line: 'pool ntp.nict.jp iburst' } 


- name: allow ip
  lineinfile: dest=/etc/chrony/chrony.conf
              line='allow 0.0.0.0/0'



- name: restart ntp
  service: name=chrony state=restarted

