---
- name: create keystone user
  script: /home/ansible/servertest/roles/mariadb/tasks/sql.sh


- name: install keystone component
  apt:
   name:
     - keystone
     - python3-openstackclient
     - apache2
     - libapache2-mod-wsgi-py3
     - python3-oauth2client


- name: /tmp/stat_test.txtのstatusを取得
  stat: path=/etc/keystone/keystone.conf
  register: file_stat


- name: keystone config backup
  command: mv /etc/keystone/keystone.conf /etc/keystone/keystone.conf.org
  when: file_stat.stat.exists


- name: basic keystone-configuration
  copy:
    src: "/etc/keystone/keystone.conf"
    dest: "/etc/keystone/keystone.conf"


- name: Perform a Keystone DB sync migrate
  command: su -s /bin/bash keystone -c "keystone-manage db_sync"


- name: initialaize key
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone 

- name: initialaize key2
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone


- name: Bootstrap keystone admin and endpoint
  command: |
    keystone-manage bootstrap --bootstrap-password adminpassword \
    --bootstrap-admin-url http://7.1.1.20:5000/v3/ \
    --bootstrap-internal-url http://7.1.1.20:5000/v3/ \
    --bootstrap-public-url http://7.1.1.20:5000/v3/ \
    --bootstrap-region-id RegionOne 
