---
- name: install nova-compute component
  apt:
    name:
      - nova-compute
      - nova-compute-kvm


- name: restart nova-compute
  service: name=nova-compute state=restarted


- name: check nova-compute
  command: "cat /root/servertest/roles/novauser/tasks/nova-result"
  register: check_nova_compute


- name: node discover
  command: su -s /bin/bash nova -c "nova-manage cell_v2 discover_hosts"
  when: "'nova-compute' in check_nova_compute.stdout"


- name: restart nova-conductor
  service: name=nova-conductor state=stopped


- name: restart nova-scheduler
  service: name=nova-scheduler state=stopped


- name: restart nova-novncproxy
  service: name=nova-novncproxy state=stopped
